# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Kenneth Duff"
description: > # this means to ignore newlines until "email:"
   Honours Student in Data Analytics at the University of Saskatchewan

email: kenneth.duff@usask.ca
#blog logo
logo: "/assets/images/avatar.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/fractal.jpeg"

name: 'Kenneth Duff'
author: 'Kenneth Duff'
author_image: "/assets/images/avatar.png"

paginate:	5

url: "http://kenduff.***.***" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	linkedin
    url:	https://www.linkedin.com/in/kenneth-duff/
    desc: Connect with me on Linkedin!
    share_url:
    share_title: 
    share_link:

  - icon:	code
    url:	https://git.cs.usask.ca/qdb802
    desc: View my school projects on Gitlab!
    share_url:
    share_title: 
    share_link: 

  - icon:	github
    url:	https://github.com/KenDuff
    desc:	View my personal projects on Github!
    share_url:
    share_title:
    share_link:
