# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Kenneth Duff"
description: > # this means to ignore newlines until "email:"
   "Honours Student in Data Analytics at the University of Saskatchewan"

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Kenneth Duff'
author: 'Kenneth Duff'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://kenduff.***.***" # the base hostname & protocol for your site
baseurl: ""

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	linkedin
    url:	https://www.linkedin.com/in/kenneth-duff/
    desc: Connect with me on Linkedin!
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	gitlab
    url:	https://about.gitlab.com/
    desc: View my school projects on Gitlab!
    share_url:
    share_title: 
    share_link: 

  - icon:	github
    url:	https://github.com/dirkfabisch
    desc:	View my personal projects on Github!
    share_url:
    share_title:
    share_link:
